"use client";
// The Bezier mark — an abstracted pen tool: a square anchor (the repo's start) and
// a round control knob (the handle you hold) joined by the handle line; the curve
// is what the agent draws. Outlined nodes; a subtle "lit" sheen via a currentColor
// gradient so it's theme-aware. Generated by design/brand/logo/explore/build-locked.mjs.
import { useId } from "react";

export function BezierMark({ className, title = "Bezier" }: { className?: string; title?: string }) {
  const id = useId().replace(/:/g, "");
  return (
    <svg viewBox="0 0 100 100" fill="none" role="img" aria-label={title} className={className}>
      <defs>
        <linearGradient id={id} gradientUnits="userSpaceOnUse" x1="22" y1="14" x2="78" y2="92">
          <stop offset="0" stopColor="currentColor" stopOpacity="1" />
          <stop offset="1" stopColor="currentColor" stopOpacity="0.62" />
        </linearGradient>
      </defs>
      <g transform="translate(-1.88 -2.63)" stroke={`url(#${id})`} strokeWidth={13} fill="none">
        <line x1="40.75" y1="34" x2="67.5" y2="34" strokeLinecap="round" />
        <path d="M40.75 34 C60.75 34 74.75 68 70.75 86" strokeLinecap="round" />
        <path d="M24 19.25 L38.75 34 L24 48.75 L9.25 34 Z" strokeLinejoin="round" />
        <circle cx="82" cy="34" r="12.5" />
      </g>
    </svg>
  );
}
